import type { Metadata } from "next";
import { Roboto, Lora } from "next/font/google";
import "../globals.scss";
import Header from "@/components/Header";
import ThemeScript from "@/components/ThemeScript";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "vietnamese"],
  weight: ["400", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "600"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Trendly mua sắm sale thả ga",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${lora.variable} antialiased`}>
        <ThemeScript />
        <Header />
        {children}
      </body>
    </html>
  );
}
