import type { Metadata } from "next";
import { Roboto, Lora } from "next/font/google";
import { cookies } from "next/headers";
import ThemeScript from "@/components/ThemeScript";
import LayoutClient from "./layoutClient";
import "../globals.scss";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin", "vietnamese"],
  weight: ["400", "700"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "600"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Trendly mua sắm sale thả ga",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const themeCookie = (await cookieStore).get("data-theme");
  const serverTheme = themeCookie?.value === "dark" ? "dark" : "light";

  return (
    <html lang="en" data-theme={serverTheme} suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body className={`${roboto.variable} ${lora.variable} antialiased`}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
